// Turn accepted proposals into rows in src/data/places.ts.
//
//   npm run apply:places
//
// Reads data/proposals/accepted.txt (one id per line, `#` comments) and
// data/proposals/places.json, and APPENDS below the generated boundary comment.
// It never rewrites or reorders an existing row, which is what makes a second
// run safe and what makes `HAND_CURATED_COUNT` mean something forever.
//
// The output then goes through normal code review as a diff, like any other
// change to a source file. That is the human gate; this script is the typing.
import { readFile, writeFile } from "node:fs/promises";
import { createServer } from "vite";

const PLACES_FILE = new URL("../src/data/places.ts", import.meta.url);
const PROPOSALS = new URL("../data/proposals/", import.meta.url);

const BOUNDARY = "// Generated by scripts/apply-places.mjs";

/** Matches the file's own one-line style, and the field order `Place` declares. */
function formatRow(row) {
  const parts = [
    `id: ${JSON.stringify(row.id)}`,
    `name: ${JSON.stringify(row.name)}`,
    `lat: ${row.lat}`,
    `lng: ${row.lng}`,
    `tags: [${row.tags.map((tag) => JSON.stringify(tag)).join(", ")}]`,
  ];
  if (row.detour !== null) parts.push(`detour: ${JSON.stringify(row.detour)}`);
  parts.push(`osm: ${JSON.stringify(row.osm)}`);
  return `  { ${parts.join(", ")} },`;
}

async function main() {
  const proposals = JSON.parse(await readFile(new URL("places.json", PROPOSALS), "utf8"));
  const wanted = (await readFile(new URL("accepted.txt", PROPOSALS), "utf8"))
    .split("\n")
    .map((line) => line.replace(/#.*$/, "").trim())
    .filter((line) => line.length > 0);

  const byId = new Map(proposals.accepted.map((row) => [row.id, row]));
  const missing = wanted.filter((id) => !byId.has(id));
  if (missing.length > 0) {
    console.error(`apply-places: ${missing.length} accepted ids are not in places.json:`);
    for (const id of missing.slice(0, 10)) console.error(`  ${id}`);
    process.exit(1);
  }

  const source = await readFile(PLACES_FILE, "utf8");

  // An id already present is a propose bug, not something to skip quietly: the
  // proposer seeds `taken` from PLACES precisely so this cannot happen, and if
  // it did, silently dropping the row would hide the fault.
  const present = wanted.filter((id) => source.includes(`id: "${id}"`));
  if (present.length > 0) {
    console.error(`apply-places: ${present.length} ids are already in places.ts:`);
    for (const id of present.slice(0, 10)) console.error(`  ${id}`);
    console.error("That is a propose bug. Nothing written.");
    process.exit(1);
  }

  // Counted by IMPORTING the module, never by scraping it - and both ways of
  // scraping it are already documented mistakes this script made in one sitting.
  // A regex over the whole file counts the 11 PRESET_ORIGINS and the 6 VIBES
  // too and answers 81 for 62; scoped to the array literal it misses `pyramid`,
  // the one entry written across several lines because it carries a source
  // comment, and answers 61. The array is the only authority on its own length.
  const vite = await createServer({
    server: { middlewareMode: true },
    appType: "custom",
    cacheDir: "node_modules/.vite-apply-places",
    optimizeDeps: { noDiscovery: true, include: [] },
  });
  let current;
  let maxPlaces;
  try {
    const module = await vite.ssrLoadModule("/src/data/places.ts");
    current = module.PLACES.length;
    maxPlaces = module.MAX_PLACES;
  } finally {
    await vite.close();
  }
  const after = current + wanted.length;
  if (after > maxPlaces) {
    // The arithmetic, printed, and nothing written. Leaving this to
    // places.test.ts would mean discovering the overshoot from a red test
    // against a file already rewritten.
    console.error(
      `apply-places: ${current} places + ${wanted.length} accepted = ${after}, ` +
        `past MAX_PLACES=${maxPlaces}. Nothing written.`,
    );
    process.exit(1);
  }

  const boundaryAt = source.indexOf(BOUNDARY);
  if (boundaryAt === -1) {
    console.error(`apply-places: could not find the generated boundary in places.ts. Nothing written.`);
    process.exit(1);
  }
  // Append after the boundary block, which ends at the last rule line.
  const ruleEnd = source.indexOf("\n", source.indexOf("// ------", source.indexOf("ODbL.", boundaryAt)));

  const rows = wanted.map((id) => formatRow(byId.get(id))).join("\n");
  const next = `${source.slice(0, ruleEnd + 1)}${rows}\n${source.slice(ruleEnd + 1)}`;
  await writeFile(PLACES_FILE, next, "utf8");

  const detours = wanted.filter((id) => byId.get(id).detour !== null).length;
  console.log(`apply-places: appended ${wanted.length} rows (${detours} detours)`);
  console.log(`  places.ts now holds ${after} of a possible ${maxPlaces}`);
  console.log(`  run npm run verify - verify-places will /locate every new row`);
}

await main();
